apiVersion: apps/v1
kind: Deployment
metadata:
  name: dentall-lab-landing-prod
  namespace: dentall-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dentall-lab-landing-prod
  template:
    metadata:
      labels:
        app: dentall-lab-landing-prod
    spec:
      containers:
        - name: dentall-lab-landing-prod
          image: gcr.io/dentaltw-info/dentall-lab/prod/landing:LAB_LANDING_VERSION_TAG
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dentall-lab-landing-prod-config-map
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8022
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8022
          ports:
            - containerPort: 8022