name: Auto-Build-Deploy-Landing-Staging
on:
  push:
    tags:
      - 'stg-*.*.*'
jobs:
  setEnv:
    if: contains( github.event.base_ref, 'master')
    runs-on: ubuntu-latest
    outputs:
      SOURCE_TAG: ${{ steps.step1.outputs.SOURCE_TAG }}
    steps:
      - uses: actions/checkout@master
      - name: Set env
        id: step1
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/*/}
          echo ${{github.event.base_ref}}
      - name: View tag
        run: |
          echo $TAG
  Combine:
    needs: setEnv
    uses: dentallio/baru/.github/workflows/buildAndDeployLanding.yml@master
    with:
      tags: landing-${{ needs.setEnv.outputs.SOURCE_TAG }}