name: Build-Baru-Landing-Production
on:
  push:
    tags:
      - 'rel-*.*.*'
env:
  PROJECT_ID: ${{ secrets.DENTALTW_GCP_PROJECT_ID }}
  SERVICE_NAME: dentall-lab
jobs:
  setEnv:
    if: contains( github.event.base_ref, 'main')
    runs-on: ubuntu-latest
    outputs:
      SOURCE_TAG: ${{ steps.step1.outputs.SOURCE_TAG }}
    steps:
      - uses: actions/checkout@master
      - name: Set env
        id: step1
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/*/}
          echo ${{github.event.base_ref}}
      - name: View tag
        run: |
          echo $TAG
  buildLandingServerToGcr:
    needs: setEnv
    if: contains( github.event.base_ref, 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.DENTALTW_GCP_SV_EMAIL }}
          service_account_key: ${{ secrets.DENTALTW_GCP_KEY }}
          project_id: ${{ secrets.DENTALTW_GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Build
        run: |
          gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME/prod/landing:${{ needs.setEnv.outputs.SOURCE_TAG }}"
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()