name: Deploy-Baru-Landing-Production
on:
  workflow_dispatch:
    ref: master
    inputs:
      tagName:
        description: 'Input version tag (rel-*.*.*)'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s/prod
    steps:
      - name: Checkout
        uses: actions/checkout@master
        # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.DENTALTW_GCP_SV_EMAIL }}
          service_account_key: ${{ secrets.DENTALTW_GCP_KEY }}
          project_id: ${{ secrets.DENTALTW_GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Deploy
        run: |
          gcloud --quiet config set project ${{ secrets.DENTALTW_GCP_PROJECT_ID }}
          gcloud --quiet config set compute/region ${{ secrets.DENTALTW_CLUSTER_REGION }}
          gcloud --quiet components install kubectl
          gcloud container clusters get-credentials ${{ secrets.DENTALTW_K8S_PROD_CLUSTER }}
          kubectl config set-context --current --namespace=${{ secrets.K8S_PROD_NAMESPACE }}
          sed -e 's|LAB_LANDING_VERSION_TAG|'"${{ github.event.inputs.tagName }}"'|g' deployment.yml | kubectl apply -f -